version: '3.8'

services:
  # --- 1. PROXY INVERSO (NGINX) ---
  proxy:
    image: nginx:alpine
    container_name: reto-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - red-reto

  # --- 2. FRONTEND ---
  frontend:
    build: ./frontend
    container_name: reto-frontend
    restart: always
    networks:
      - red-reto

  # --- 3. BACKEND (Tu Laravel con Apache) ---
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: reto-backend
    restart: always
    volumes:
      - ./backend:/var/www/html
    networks:
      - red-reto
    depends_on:
      - db

  # --- 4. BASE DE DATOS ---
  db:
    image: mysql:8.0
    container_name: reto-db
    restart: always
    environment:
      MYSQL_DATABASE: reto_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - red-reto

  # --- 5. PHPMYADMIN ---
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: reto-pma
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - red-reto

networks:
  red-reto:
    driver: bridge

volumes:
  db_data: